language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - rm -rf .coverage
  - coverage erase
  - pytest tests --cov=jobs-scraper --cov-report xml:coverage.xml
  - coverage combine --append || true
  - coverage report